class Actions:
    shoot   = "shoot"
    shield  = "shield"
    grenade = "grenade"
    reload  = "reload"
    logout  = "logout"
    grenade1 = "yes1"
    grenade2 = "yes2"
    vest1 = "bullet2"
    vest2 = "bullet1"